version: "3.9"
services:
  prometheus:
    image: bitnami/prometheus
    ports:
      - mode: ingress
        target: 3000
        published: 3000
        protocol: tcp
    network_mode: host
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - type: volume
        source: prometheus-volumes
        target: /opt/bitnami/prometheus/conf
        read_only: false
  grafana:
    image: grafana/grafana-oss:latest
    pull_policy: always
    network_mode: host
    container_name: grafana
    depends_on:
      - prometheus
    restart: unless-stopped
    ports:
      - mode: ingress
        target: 9090
        published: 9090
        protocol: tcp
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
volumes:
  prometheus-volume: { }
