server:
    port: 8081
spring:
    profiles:
        active:
            - "dev"
    application:
        name: spring-kafka

# metrics conf
management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
        - health
        - metrics
        - info
        - prometheus